#!/usr/bin/python3
# SPDX-FileCopyrighiText: 2022 Yuna Hayashi s22c1105lv@s.chibakoudai.jp
# SPDX-License-Identifier: BSD-3-Clause

import sys

x=0.0
for n in sys.argv[1:]:
    x += float(n)

print(x)
