#!/usr/bin/python3
# SPDX-FileCopyrighiText: 2022 Yuna Hayashi s22c1105lv@s.chibakoudai.jp
# SPDX-License-Identifier: BSD-3-Clause 

import sys


def tonum(s):
    try:
        return int(s)
    except:
        return float(s)

ans = 0
for line in sys.stdin:
    line = line.rstrip()
    ans += tonum(line)

print(ans)
