name: test
on: push
jobs: 
        test:
                runs-on: ububtu-latest
                steps:
                - uses: actions/checkout@v3
                - name: All test
                  run: bash -xv ./test.bash
